// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xrTpt0ZFH_eoR_qUoN2idPE9Lw5aBVg',
    appId: '1:813673080572:web:a51507ea415a5ba6251979',
    messagingSenderId: '813673080572',
    projectId: 'flutter-chatapp-85c43',
    authDomain: 'flutter-chatapp-85c43.firebaseapp.com',
    storageBucket: 'flutter-chatapp-85c43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzV1EpC80FBrbVvpnpVyL16qoO3qiGuos',
    appId: '1:813673080572:android:b1fbe8708e69f5b7251979',
    messagingSenderId: '813673080572',
    projectId: 'flutter-chatapp-85c43',
    storageBucket: 'flutter-chatapp-85c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzqSbWkrUoz9SO1SyfKN7husQigwDlf4U',
    appId: '1:813673080572:ios:aa2a3f9a0862b17f251979',
    messagingSenderId: '813673080572',
    projectId: 'flutter-chatapp-85c43',
    storageBucket: 'flutter-chatapp-85c43.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzqSbWkrUoz9SO1SyfKN7husQigwDlf4U',
    appId: '1:813673080572:ios:1a02c7cacfefa923251979',
    messagingSenderId: '813673080572',
    projectId: 'flutter-chatapp-85c43',
    storageBucket: 'flutter-chatapp-85c43.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseBloc.RunnerTests',
  );
}
